defmodule GameOfLife.Markdown do
  alias GameOfLife.Board

  @shortdoc "Generate a Markdown table from a Game of Life board"
  @moduledoc @shortdoc

  @autogenerated_md_begin "<!-- begin auto-generated game of life board -->"
  @autogenerated_md_end "<!-- end auto-generated game of life board -->"

  @spec replace_markdown(binary(), Board.t()) :: binary()
  def replace_markdown(prev_markdown, board) do
    md = to_markdown(board)

    pat_begin = Regex.escape(@autogenerated_md_begin)
    pat_end = Regex.escape(@autogenerated_md_end)
    pattern = ~r/#{pat_begin}.*#{pat_end}/s

    if Regex.match?(pattern, prev_markdown) do
      String.replace(prev_markdown, pattern, md)
    else
      "#{prev_markdown}\n#{md}"
    end
  end

  @spec to_markdown(Board.t()) :: binary()
  def to_markdown(board) do
    "#{@autogenerated_md_begin}

#{to_markdown_string(board)}
#{@autogenerated_md_end}"
  end

  @spec to_markdown_string(Board.t()) :: binary()
  defp to_markdown_string(board) do
    %Board{height: height, width: width} = board

    header =
      0..width
      |> Enum.map(fn j -> if(j > 0, do: "#{j - 1}", else: " ") end)
      |> Enum.map_join(" | ", fn x -> String.pad_trailing(x, 3) end)
      |> (&("| " <> &1 <> " |")).()

    separator =
      0..width
      |> Enum.map(fn _ -> " --- " end)
      |> Enum.intersperse("|")
      |> Enum.join("")
      |> (&("|" <> &1 <> "|")).()

    body =
      0..(height - 1)
      |> Enum.map_join("\n", fn i ->
        row = 0..(width - 1) |> Enum.map(fn j -> Board.at(board, i, j) end)

        "| #{String.pad_trailing("#{i}", 3)} | #{row_to_markdown(row)} |"
      end)

    [header, separator, body, ""] |> Enum.join("\n")
  end

  @spec row_to_markdown(list(Board.cell())) :: binary()
  defp row_to_markdown(row) do
    Enum.map_join(row, " | ", &if(&1 == 1, do: "◼️ ", else: "◻️ "))
  end
end
